-- Create database 'hbtn_0d_usa'
-- Ifdb aeady exists, script should notfail.
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;

-- Create table 'states' in db 'hbtn_0d_usa'.
-- ud IT unique autogenerated not null and primary key-- name VARCHAR(256) not null
-- if table arleady exists, script should not fail.
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states
(
	id INT UNIQUE AUTO_INCREMENT NOT NULL.
	name VARCHAR(256) nNOT NULL,
	name VARTCHAR(256) NOT NULL,
	PRIMARY KEY (id)
);
